import asyncio
import uuid
from datetime import datetime
from core.event_bus import EventBus
from common.models import VolatilityMetrics, LiquiditySnapshot, AnomalyEvent
from signals.models import IntelligentAlert

class AlertIntelligenceService:
    def __init__(self, event_bus: EventBus):
        self.event_bus = event_bus

    async def start(self):
        self.event_bus.subscribe(VolatilityMetrics, self._on_vol)
        self.event_bus.subscribe(LiquiditySnapshot, self._on_liq)
        self.event_bus.subscribe(AnomalyEvent, self._on_anomaly)

    async def _on_vol(self, vol):
        if vol.is_spike:
            await self._trigger("VOL_EXPANSION", "high", f"Vol spike: {vol.realized_volatility:.2%}")

    async def _on_liq(self, liq):
        if liq.spread > 0.01:
            await self._trigger("LIQUIDITY_STRESS", "medium", "Spread widening")

    async def _on_anomaly(self, event):
        await self._trigger("STRUCTURAL_SHOCK", "high", event.description)

    async def _trigger(self, alert_type, severity, message):
        alert = IntelligentAlert(
            id=str(uuid.uuid4()),
            symbol="GLOBAL",
            timestamp=datetime.now(),
            alert_type=alert_type,
            severity=severity,
            confidence=0.8,
            message=message,
            explanation="Generated by real-time microstructure analysis.",
            affected_metrics=[],
            regime_context="UNKNOWN"
        )
        await self.event_bus.publish(alert)
